# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2300c17e5c99708dc681b74a217f59efbc0235d77456656415b57e30046f3fe1706b9375d8b44c9c5c7a7529d1d7ed93969c177979952772568d03560c7a0e96

test:
  secret_key_base: 81ffd6842ae279192eb7abee4b4b6fd99a72297dd6db2956c89bba9b5588f0b58357e0a72f3f0bc40e90315582e4621a7e9f0b7f93e22993511c17069c5aba83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
